# Generated by Django 4.0 on 2023-02-25 18:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scholarly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 25, 18, 41, 56, 696084, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='file',
            field=models.FileField(max_length=254, upload_to='scholarly/publications'),
        ),
    ]
